import fs from 'fs';
import path from 'path';

const PAGES_DIR = path.join(__dirname, '../src/pages');
const REGISTRY_FILE = path.join(__dirname, '../src/registry.ts');

interface ChapterMetadata {
  file: string;
  component: string;
  number?: string;
  title?: string;
  subtitle?: string;
  group?: string;
}

function extractMetadata(filePath: string): ChapterMetadata {
  const content = fs.readFileSync(filePath, 'utf-8');
  const fileName = path.basename(filePath);
  const componentName = fileName.replace('.tsx', '').replace(/-/g, '');

  // Extract group from comment: // Group: NAME
  const groupMatch = content.match(/\/\/\s*Group:\s*([^\n\r]+)/);
  const group = groupMatch ? groupMatch[1].trim() : undefined;

  // Extract ChapterTitle props
  const numMatch = content.match(/number="(\d+)"/) || content.match(/\/\/\s*Number:\s*(\d+)/);
  const titleMatch = content.match(/title="([^"]+)"/) || content.match(/\/\/\s*Title:\s*([^\n\r]+)/);
  const subtitleMatch = content.match(/subtitle="([^"]+)"/) || content.match(/\/\/\s*Subtitle:\s*([^\n\r]+)/);

  return {
    file: fileName,
    component: componentName,
    number: numMatch ? (Array.isArray(numMatch) ? numMatch[1] : numMatch[1]).trim() : undefined,
    title: titleMatch ? (Array.isArray(titleMatch) ? titleMatch[1] : titleMatch[1]).trim() : undefined,
    subtitle: subtitleMatch ? (Array.isArray(subtitleMatch) ? subtitleMatch[1] : subtitleMatch[1]).trim() : undefined,
    group,
  };
}

async function sync() {
  const files = fs.readdirSync(PAGES_DIR)
    .filter(f => f.endsWith('.tsx'))
    .sort();

  const metadata = files.map(f => extractMetadata(path.join(PAGES_DIR, f)));

  // Generate imports
  const imports = metadata.map(m => `import ${m.component} from './pages/${m.file.replace('.tsx', '')}';`).join('\n');

  // Generate pages list
  const pagesList = metadata.map(m => m.component).join(',\n  ');

  // Generate TOC groups
  const groups: Record<string, any[]> = {};
  metadata.forEach(m => {
    if (m.group && m.number) {
      if (!groups[m.group]) groups[m.group] = [];
      groups[m.group].push({
        num: m.number,
        title: m.title,
        subtitle: m.subtitle,
      });
    }
  });

  const registryContent = `/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated by scripts/sync-project.ts
 */
import React from 'react';
${imports}

export const allPages = [
  ${pagesList}
];

export const tocGroups = ${JSON.stringify(groups, null, 2)};
`;

  fs.writeFileSync(REGISTRY_FILE, registryContent);
  console.log('Registry generated at src/registry.ts');
}

sync();
