import fs from 'fs';
import path from 'path';
import { MANIFEST } from '../src/manifest';

const PAGES_DIR = path.join(__dirname, '../src/pages');
const REGISTRY_FILE = path.join(__dirname, '../src/registry.ts');

// Chrome folders aren't manifest chapters; they render at fixed book positions.
const CHROME_START = ['01-cover', '02-toc'];
const CHROME_END = ['15-conclusion'];

function toIdentifier(relPath: string): string {
  // Convert "03-introduction/01-introduction" -> "Page_03Introduction_01Introduction".
  const pascal = relPath
    .split('/')
    .map((segment) =>
      segment
        .split('-')
        .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
        .join(''),
    )
    .join('_')
    .replace(/[^a-zA-Z0-9_]/g, '');
  return `Page_${pascal}`;
}

/**
 * Walk PAGES_DIR finding all .tsx files (relative paths without extension),
 * sorted. Used so every page file is included, even ones not in the manifest.
 */
function findAllPageFiles(): string[] {
  const files: string[] = [];

  function walk(dir: string) {
    const entries = fs.readdirSync(dir, { withFileTypes: true });
    for (const entry of entries) {
      const res = path.join(dir, entry.name);
      if (entry.isDirectory()) {
        walk(res);
      } else if (entry.isFile() && entry.name.endsWith('.tsx')) {
        files.push(path.relative(PAGES_DIR, res).replace(/\.tsx$/, ''));
      }
    }
  }

  walk(PAGES_DIR);
  return files.sort();
}

function sync() {
  const allFiles = findAllPageFiles();
  const claimed = new Set<string>();

  const filesInDirs = (dirs: string[]): string[] => {
    const out: string[] = [];
    for (const dir of dirs) {
      for (const f of allFiles) {
        if (f.startsWith(dir + '/') && !claimed.has(f)) {
          out.push(f);
          claimed.add(f);
        }
      }
    }
    return out;
  };

  // 1. Fixed chrome at the start (all files in cover/TOC folders, sorted).
  const startPaths = filesInDirs(CHROME_START);

  // 2. Manifest chapters and their directory siblings, in manifest order.
  const middlePaths: string[] = [];
  MANIFEST.forEach((group) => {
    group.chapters.forEach((ch) => {
      const entryPath = ch.entryPage;
      if (!allFiles.includes(entryPath)) {
        console.error(
          `sync: manifest chapter ${ch.num} ("${ch.title}") entryPage '${entryPath}' has no matching file under src/pages/`,
        );
        process.exit(1);
      }
      if (claimed.has(entryPath)) return;
      middlePaths.push(entryPath);
      claimed.add(entryPath);

      // All files sharing the entry page's directory that no other entry claimed.
      const chDir = path.dirname(entryPath);
      allFiles
        .filter((f) => f.startsWith(chDir + '/') && !claimed.has(f))
        .sort()
        .forEach((f) => {
          middlePaths.push(f);
          claimed.add(f);
        });
    });
  });

  // 3. Conclusion / back-cover chrome, appended at the end.
  const endPaths = filesInDirs(CHROME_END);

  // 4. Anything not claimed by chrome or the manifest (defensive — keeps the page
  //    in the book rather than dropping it silently, just before the conclusion).
  const leftovers = allFiles.filter((f) => !claimed.has(f)).sort();
  if (leftovers.length > 0) {
    console.warn(`sync: ${leftovers.length} page(s) not in manifest or chrome, placed before conclusion: ${leftovers.join(', ')}`);
  }

  const orderedRelPaths = [...startPaths, ...middlePaths, ...leftovers, ...endPaths];

  const pages = orderedRelPaths.map((relPath) => ({
    relPath,
    component: toIdentifier(relPath),
  }));

  const imports = pages
    .map((p) => `import ${p.component} from './pages/${p.relPath}';`)
    .join('\n');

  const pagesList = pages.map((p) => p.component).join(',\n  ');

  const registryContent = `/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated by scripts/sync-project.ts
 */
${imports}

export const allPages = [
  ${pagesList}
];
`;

  fs.writeFileSync(REGISTRY_FILE, registryContent);
  console.log(`Registry generated at src/registry.ts (${pages.length} pages)`);
}

sync();
