import fs from 'fs';
import path from 'path';
import { MANIFEST } from '../src/manifest';

const PAGES_DIR = path.join(__dirname, '../src/pages');
const REGISTRY_FILE = path.join(__dirname, '../src/registry.ts');

function toIdentifier(relPath: string): string {
  // Convert "03-introduction/01-introduction" -> "Page_03_Introduction_01_Introduction".
  const pascal = relPath
    .split('/')
    .map((segment) =>
      segment
        .split('-')
        .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
        .join(''),
    )
    .join('_')
    .replace(/[^a-zA-Z0-9_]/g, '');
  return `Page_${pascal}`;
}

/** 
 * Walk PAGES_DIR finding all .tsx files.
 * We'll use this to ensure all files are included, even those not in the manifest.
 */
function findAllPageFiles(): string[] {
  const files: string[] = [];
  
  function walk(dir: string) {
    const entries = fs.readdirSync(dir, { withFileTypes: true });
    for (const entry of entries) {
      const res = path.join(dir, entry.name);
      if (entry.isDirectory()) {
        walk(res);
      } else if (entry.isFile() && entry.name.endsWith('.tsx')) {
        files.push(path.relative(PAGES_DIR, res).replace('.tsx', ''));
      }
    }
  }

  walk(PAGES_DIR);
  return files.sort();
}

async function sync() {
  const allFiles = findAllPageFiles();
  
  // 1. Start with fixed chrome
  const orderedRelPaths: string[] = [
    '01-cover/01-cover',
    '02-toc/01-toc'
  ];

  // 2. Add manifest chapters and their directory siblings
  const manifestFiles = new Set<string>();
  
  MANIFEST.forEach(group => {
    group.chapters.forEach(ch => {
      const entryPath = ch.entryPage;
      if (manifestFiles.has(entryPath)) return;
      manifestFiles.add(entryPath);
      orderedRelPaths.push(entryPath);

      // Find all files in the same directory as the entry page that haven't
      // already been claimed by another manifest entry sharing the directory.
      const chDir = path.dirname(entryPath);
      const siblings = allFiles
        .filter(f => f.startsWith(chDir + '/') && f !== entryPath && !manifestFiles.has(f))
        .sort();

      siblings.forEach(s => {
        orderedRelPaths.push(s);
        manifestFiles.add(s);
      });
    });
  });

  // 3. Add any leftovers (files not in manifest or not siblings of manifest entries)
  const leftovers = allFiles.filter(f => 
    !manifestFiles.has(f) && 
    f !== '01-cover/01-cover' && 
    f !== '02-toc/01-toc' &&
    f !== '15-conclusion/01-conclusion'
  );
  
  orderedRelPaths.push(...leftovers);
  
  // 4. End with conclusion
  if (allFiles.includes('15-conclusion/01-conclusion')) {
    orderedRelPaths.push('15-conclusion/01-conclusion');
  }

  const pages = orderedRelPaths.map(relPath => ({
    relPath,
    component: toIdentifier(relPath)
  }));

  const imports = pages
    .map((p) => `import ${p.component} from './pages/${p.relPath}';`)
    .join('\n');

  const pagesList = pages.map((p) => p.component).join(',\n  ');

  // Simple groups for TOC consumption
  const tocGroups: Record<string, any[]> = {};
  MANIFEST.forEach(g => {
    tocGroups[g.id] = g.chapters.map(ch => ({
      num: ch.num,
      title: ch.title,
      subtitle: ch.subtitle
    }));
  });

  const registryContent = `/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated by scripts/sync-project.ts
 */
import React from 'react';
${imports}

export const allPages = [
  ${pagesList}
];

export const tocGroups = ${JSON.stringify(tocGroups, null, 2)};
`;

  fs.writeFileSync(REGISTRY_FILE, registryContent);
  console.log(`Registry generated at src/registry.ts (${pages.length} pages)`);
}

sync();
