/**
 * Document — Root assembly file
 *
 * Reads `allPages` from `./registry` (auto-generated by `scripts/sync-project.ts`
 * on every `pnpm sync` / `pnpm build`) and renders each page component inside
 * one `<Document>` with PDF metadata. Adding a page = drop a file in src/pages/
 * matching the directory + manifest convention; sync wires it in.
 *
 * Page order: Cover → TOC → Ch01–Ch12 → Conclusion. The page list is whatever
 * the generated registry contains — see scripts/sync-project.ts.
 */
import React from 'react';
import { Document } from '@react-pdf/renderer';
import { allPages } from './registry';

const EbookDocument: React.FC = () => (
  <Document
    title="React-PDF + AI: The Builder's Guide to Premium PDF Generation"
    author="Landon Miles"
    subject="Best practices for using @react-pdf/renderer with AI coding agents"
    keywords="react-pdf, AI, PDF generation, design systems, best practices"
    creator="react-pdf-gen"
  >
    {allPages.map((Page, index) => (
      <Page key={index} />
    ))}
  </Document>
);

export default EbookDocument;
